/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_cn_opus_tool_OpusTool */

#ifndef _Included_com_cn_opus_tool_OpusTool
#define _Included_com_cn_opus_tool_OpusTool
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_cn_opus_tool_OpusTool
 * Method:    nativeGetString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_cn_opus_tool_OpusTool_nativeGetString
  (JNIEnv *, jobject);

/*
 * Class:     com_cn_opus_tool_OpusTool
 * Method:    encode_opus_file
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_cn_opus_tool_OpusTool_encode_1opus_1file
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_cn_opus_tool_OpusTool
 * Method:    decode_opus_file
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_cn_opus_tool_OpusTool_decode_1opus_1file
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
